require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec # or rubocop-minitest

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/MethodLength:
  Max: 100

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'