# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/animal_requests', type: :request do
  # AnimalRequest. As you add validations to AnimalRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      AnimalRequest.create! valid_attributes
      get animal_requests_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      animal_request = AnimalRequest.create! valid_attributes
      get animal_request_url(animal_request)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_animal_request_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      animal_request = AnimalRequest.create! valid_attributes
      get edit_animal_request_url(animal_request)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new AnimalRequest' do
        expect do
          post animal_requests_url, params: { animal_request: valid_attributes }
        end.to change(AnimalRequest, :count).by(1)
      end

      it 'redirects to the created animal_request' do
        post animal_requests_url, params: { animal_request: valid_attributes }
        expect(response).to redirect_to(animal_request_url(AnimalRequest.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new AnimalRequest' do
        expect do
          post animal_requests_url, params: { animal_request: invalid_attributes }
        end.to change(AnimalRequest, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post animal_requests_url, params: { animal_request: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested animal_request' do
        animal_request = AnimalRequest.create! valid_attributes
        patch animal_request_url(animal_request), params: { animal_request: new_attributes }
        animal_request.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the animal_request' do
        animal_request = AnimalRequest.create! valid_attributes
        patch animal_request_url(animal_request), params: { animal_request: new_attributes }
        animal_request.reload
        expect(response).to redirect_to(animal_request_url(animal_request))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        animal_request = AnimalRequest.create! valid_attributes
        patch animal_request_url(animal_request), params: { animal_request: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested animal_request' do
      animal_request = AnimalRequest.create! valid_attributes
      expect do
        delete animal_request_url(animal_request)
      end.to change(AnimalRequest, :count).by(-1)
    end

    it 'redirects to the animal_requests list' do
      animal_request = AnimalRequest.create! valid_attributes
      delete animal_request_url(animal_request)
      expect(response).to redirect_to(animal_requests_url)
    end
  end
end
